apiVersion: apps/v1
kind: Deployment
metadata:
  name: challengeone
  labels:
    app: challengeone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: challengeone
  template:
    metadata:
      labels:
        app: challengeone
    spec:
      containers:
        - name: challengeone
          image: thiagotierre/challengeone:1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: challengeone-config
            - secretRef:
                name: challengeone-db-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
